### ISSUE TITLE
possible to inject into HTML page ?

### ISSUE THREAD

**Issue by idcrook** [aspirewit/hexo-tag-easy-charts#10]
It would be handy if this (or an associated plugin) could inject the `<script>` include into the webpage `<head>` instead of requiring it to be manually added.
Something similar to:

https://github.com/hexojs/hexo-browsersync/blob/master/lib/browsersync.js#L37-L47

**Comment by aspirewit** [comment]
@idcrook Thank you for your feedback! I've implemented this feature based on your proposal, you only need to upgrade to `0.2.0`.

**Comment by aspirewit** [comment]
@idcrook I'm extremely sorry for my carelessnes, server_middleware only works when the hexo service is running, I will look for other ways.

**Comment by idcrook** [comment]
that is OK. it was something as a suggestion to make the plugin more "magical"
