### ISSUE TITLE
Is it possible to reduce the size of  viewport

### ISSUE THREAD

**Issue by souravray** [aspirewit/hexo-tag-easy-charts#15]
This is the problem
![Image of Yaktocat](http://image.prntscr.com/image/ca164f6b4d4f453c966e1742009fe01d.png)

**Comment by souravray** [comment]
At this moment following values are hard - codedvie-port height 480px and radius of the pie chart 50% 
I have extended the plugin and changed the hard coded values, You can see the final output  @ [http://raysourav.com/resume/]
 
These parameters needed to be configurable. If I get time I will create PR for the same.

**Comment by aspirewit** [comment]
@souravray thx, I Look forward to your PR.
