### ISSUE TITLE
time based charts

### ISSUE THREAD

**Issue by oupala** [aspirewit/hexo-tag-easy-charts#18]
Is there a way to display time based charts?

If yes, can you add an example?

My dataset is based on years, but I don't get the data for each year. To charts has to display the point at the right place depending on the date (year).

**Comment by aspirewit** [comment]
@oupala This plugin only supports simple two-dimensional data.

**Comment by aspirewit** [comment]
Can you provide some sample data to me?

`Time based charts`, my understanding is like that, do you think it is correct?
```
{% barchart 'By Year' %}
Fruit | 2012 | 2013 | 2014 | 2015 | 2016 | 2017
Durian | 80 | 73 | 72 | 62 | 83 | 65
Clementine | 56 | 60 | 50 | 58 | 57 | 63
Durian | 61 | 72 | 85 | 76 | 69 | 88
Mulberry | 83 | 91 | 98 | 82 | 62 | 86
Papaya | 54 | 58 | 67 | 64 | 50 | 93
{% endbarchart %}
```

![image](https://cloud.githubusercontent.com/assets/9118112/24290279/615e7eae-10bf-11e7-856d-c4c8e80ffe34.png)

**Comment by oupala** [comment]
Sure I'll try to give you as much information as possible.

For time based charts, I would more imagine a linechart. But imagine that the time serie is missing some data. You don't have the data for one year, you should have the missing year displayed on screen, event with no date.

```
{% linechart 'Linechart with Vertical Headings' %}
Date | Sales
2012 | 56
2013 | 85
2016 | 68
2017 | 53
{% endlinechart %}
```

Years 2014 and 2015 are missing, but they should appear on the graph.

And now, imagine that the date is not a year, but a specific day:

```
{% linechart 'Linechart with Vertical Headings' %}
Date | Sales
2012-01-01 | 56
2013-03-28 | 85
2015-07-01 | 93
2016-12-25 | 68
2017-10-28 | 53
{% endlinechart %}
```

Each data do not represent a whole year, but just an event on a specific day. The event should be represented on the timeline, at the moment it happened.

Do you see what I mean?

Some example from [metricsgraphicsjs](https://www.metricsgraphicsjs.org/examples.htm).
